
# checkout this url for more information about the flags
# https://www.rfc-editor.org/rfc/rfc3501 
class SearchKeyword:
    ALL = 'ALL'
    ANSWERED = 'ANSWERED'
    BCC = 'BCC'
    BEFORE = 'BEFORE'
    BODY = 'BODY'
    CC = 'CC'
    DELETED = 'DELETED'
    DRAFT = 'DRAFT'
    FLAGGED = 'FLAGGED'
    FROM = 'FROM'
    HEADER = 'HEADER'
    KEYWORD = 'KEYWORD'
    LARGER = 'LARGER'
    NEW = 'NEW'
    NOT = 'NOT'
    OLD = 'OLD'
    ON = 'ON'
    OR = 'OR'
    RECENT = 'RECENT'
    SEEN = 'SEEN'
    SENTBEFORE = 'SENTBEFORE'
    SENTON = 'SENTON'
    SENTSINCE = 'SENTSINCE'
    SINCE = 'SINCE'
    SMALLER = 'SMALLER'
    SUBJECT = 'SUBJECT'
    TEXT = 'TEXT'
    TO = 'TO'
    UID = 'UID'
    UNANSWERED = 'UNANSWERED'
    UNDELETED = 'UNDELETED'
    UNDRAFT = 'UNDRAFT'
    UNFLAGGED = 'UNFLAGGED'
    UNKEYWORD = 'UNKEYWORD'
    UNSEEN = 'UNSEEN'
